### ISSUE TITLE
How can I be 100% sure that a code works?

### ISSUE THREAD

**Issue by TheBackdoor** [Infinium1/NitroGenerator#1]
The checker checks only if the GET req dont failed but not if the code is valid.
How can I make a code checker?

**Comment by Infinium1** [comment]
If you change it a bit to try it with a code that you know works, it will respond without an error. There might be a chance that if it was recently redeemed it will still say it is valid, but after a few days it seems like it goes back to being invalid (by saying "invalid" I mean the api returns null or something, I forget exactly what it returns)

**Comment by Infinium1** [comment]
So basically it will only show invites as working if they are unclaimed or have been claimed like 1 day ago (again, not sure how long it is). To be 100% sure you can change the response handling as I think if it is claimed but not yet called invalid it will return something different than if it has never been claimed (hope that makes sense). If u wanna make a PR for that, go ahead, but this method isn't very good (at all) and I don't plan on updating this in the future.
